version: "3.8"
services:
  backend-flask:
    environment:
      - FRONTEND_URL="https://3000-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      - BACKEND_URL="https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      - OTEL_SERVICE_NAME:"${HONEYCOMB_SERVICE_NAME}"
      - OTEL_EXPORTER_OTLP_ENDPOINT :"https://api.honeycomb.io"
      - OTEL_EXPORTER_OTLP_HEADERS :"x-honeycomb-team=${HONEYCOMB_API_KEY}"
    build: ./backend-flask
    ports:
      - 4567:4567
    volumes:
      - ./backend-flask:/backend-flask
  frontend-react-js:
    environment:
      REACT_APP_BACKEND_URL: "https://4567-${GITPOD_WORKSPACE_ID}.${GITPOD_WORKSPACE_CLUSTER_HOST}"
      REACT_APP_AWS_PROJECT_REGION:  "eu-north-1"
      REACT_APP_AWS_COGNITO_REGION: "eu-north-1"
      REACT_APP_AWS_USER_POLLS_ID: "eu-north-1_c0wKALwPZ"
      REACT_APP_AWS_USER_POOLS_WEB_CLIENT_ID: "2g53mpg9af7v8gq5j91a2gtej1"
    build: ./frontend-react-js
    ports:
      - 3000:3000
    volumes:
      - ./frontend-react-js:/frontend-react-js

networks:
  internal-network:
    driver: bridge
    name: cruddur
